import type { Metadata } from 'next';
import localFont from 'next/font/local';
import 'normalize.css';
import './globals.css';
import Navbar from '../components/shared/navbar/Navbar';
import { ThemeProvider } from '@/providers/themeProvider';
import Footer from '@/components/shared/footer/Footer';
import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/providers/authProvider';
import { CartProvider } from '@/providers/shopingCardProvider';
import 'leaflet/dist/leaflet.css';
import { QueryProvider } from '@/providers/queryProvider';

const estedad = localFont({
  src: './fonts/EstedadKSHD-wght.woff2',
  variable: '--font-estedad',
  weight: '100 900',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  intercepting,
}: {
  children: React.ReactNode;
  intercepting: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="fa-Ir" className={estedad.className} suppressHydrationWarning>
      <body
        className={`antialiased dark:bg-background-1 selection:bg-tint-1 selection:text-gray-7`}
      >
        <QueryProvider>
          <AuthProvider>
            <CartProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem
              >
                <>
                  <Navbar />
                  {children}
                  {intercepting}
                  <Toaster
                    richColors
                    closeButton
                    dir="rtl"
                    className={estedad.className}
                    position="top-right"
                  />
                  <Footer />
                </>
              </ThemeProvider>
            </CartProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
