import type { Metadata } from 'next';
import localFont from 'next/font/local';
import 'normalize.css';
import './globals.css';
import Navbar from '../components/shared/navbar/Navbar';
import { ThemeProvider } from '@/components/shared/themeProvider';
import Footer from '@/components/shared/footer/Footer';
import { Toaster } from '@/components/ui/sonner';
import { getServerSession } from 'next-auth';
import { authOption } from './api/auth/[...nextauth]/route';
import AuthProvider from '@/components/shared/authProvider';

const estedad = localFont({
  src: './fonts/Estedad[KSHD,wght].woff2',
  variable: '--font-estedad',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  intercepting,
}: {
  children: React.ReactNode;
  intercepting: React.ReactNode;
}) {
  const session = await getServerSession(authOption)
  return (
    <html dir="rtl" lang="fa-Ir">
      <body
        className={`font-estedad antialiased dark:bg-background-1 selection:bg-tint-1 selection:text-gray-7`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            
          >
            <>
              {session?.user?.name}
              <Navbar />
              {children}
              {intercepting}
              <Toaster
                richColors
                closeButton
                dir="rtl"
                className="font-estedad"
                position="top-right"
              />
              <Footer />
            </>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
