import type { Metadata } from "next";
import localFont from "next/font/local";
import 'normalize.css';
import "./globals.css";
import Navbar from "../components/shared/navbar/Navbar";
import { ThemeProvider } from "@/components/shared/themeProvider";
import Footer from "@/components/shared/footer/Footer";



const estedad = localFont({
  src:"./fonts/Estedad[KSHD,wght].woff2",
  variable:"--font-estedad",
  weight:"100 900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa-Ir" >
      <body
        className={`${estedad.variable} font-estedad antialiased dark:bg-background-1 selection:bg-tint-1 selection:text-gray-7`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
            >
            <Navbar/>
            {children}
            <Footer/>
          </ThemeProvider>
      </body>
    </html>
  );
}
